"""esquema inicial

Revision ID: bb05c596672e
Revises: 
Create Date: 2026-07-20 18:39:54.406227

"""
from alembic import op
import sqlalchemy as sa


revision = 'bb05c596672e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estados',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('estado')
    )
    op.create_table('motivos_incidencia',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('motivo', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('motivo')
    )
    op.create_table('tipos_notificacion',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tipo')
    )
    op.create_table('tipos_usuarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tipo', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tipo')
    )
    op.create_table('zonas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('sectores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('id_zona', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_zona'], ['zonas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sectores_id_zona'), 'sectores', ['id_zona'], unique=False)
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('codigo_usuario', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('apellido_paterno', sa.String(length=100), nullable=False),
    sa.Column('apellido_materno', sa.String(length=100), nullable=True),
    sa.Column('contrasena_hash', sa.String(length=255), nullable=False),
    sa.Column('id_tipo_usuario', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_tipo_usuario'], ['tipos_usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_codigo_usuario'), 'usuarios', ['codigo_usuario'], unique=True)
    op.create_table('rutas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('hora_inicio', sa.Time(), nullable=True),
    sa.Column('hora_fin', sa.Time(), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rutas_id_usuario'), 'rutas', ['id_usuario'], unique=False)
    op.create_table('ubicaciones',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_sector', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_sector'], ['sectores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contenedores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('codigo_contenedor', sa.String(length=50), nullable=False),
    sa.Column('capacidad_max', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('id_ubicacion', sa.Integer(), nullable=False),
    sa.Column('id_estado', sa.Integer(), nullable=False),
    sa.Column('nivel_actual', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['id_estado'], ['estados.id'], ),
    sa.ForeignKeyConstraint(['id_ubicacion'], ['ubicaciones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contenedores_codigo_contenedor'), 'contenedores', ['codigo_contenedor'], unique=True)
    op.create_table('detalles_rutas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_ruta', sa.Integer(), nullable=False),
    sa.Column('id_contenedor', sa.Integer(), nullable=False),
    sa.Column('id_estado', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_contenedor'], ['contenedores.id'], ),
    sa.ForeignKeyConstraint(['id_estado'], ['estados.id'], ),
    sa.ForeignKeyConstraint(['id_ruta'], ['rutas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_detalles_rutas_id_contenedor'), 'detalles_rutas', ['id_contenedor'], unique=False)
    op.create_index(op.f('ix_detalles_rutas_id_ruta'), 'detalles_rutas', ['id_ruta'], unique=False)
    op.create_table('incidencias',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_contenedor', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('fecha_hora', sa.DateTime(), nullable=False),
    sa.Column('id_motivo', sa.Integer(), nullable=False),
    sa.Column('comentario', sa.Text(), nullable=True),
    sa.Column('id_estado', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_contenedor'], ['contenedores.id'], ),
    sa.ForeignKeyConstraint(['id_estado'], ['estados.id'], ),
    sa.ForeignKeyConstraint(['id_motivo'], ['motivos_incidencia.id'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incidencias_id_contenedor'), 'incidencias', ['id_contenedor'], unique=False)
    op.create_table('notificaciones',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('contenido', sa.Text(), nullable=False),
    sa.Column('id_contenedor', sa.Integer(), nullable=False),
    sa.Column('id_tipo_notificacion', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_contenedor'], ['contenedores.id'], ),
    sa.ForeignKeyConstraint(['id_tipo_notificacion'], ['tipos_notificacion.id'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('registros_nivel',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_contenedor', sa.Integer(), nullable=False),
    sa.Column('fecha_hora', sa.DateTime(), nullable=False),
    sa.Column('nivel_porcentaje', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('origen', sa.Enum('sensor', 'manual', name='origenregistro'), nullable=False),
    sa.ForeignKeyConstraint(['id_contenedor'], ['contenedores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_registros_nivel_fecha_hora'), 'registros_nivel', ['fecha_hora'], unique=False)
    op.create_index(op.f('ix_registros_nivel_id_contenedor'), 'registros_nivel', ['id_contenedor'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_registros_nivel_id_contenedor'), table_name='registros_nivel')
    op.drop_index(op.f('ix_registros_nivel_fecha_hora'), table_name='registros_nivel')
    op.drop_table('registros_nivel')
    op.drop_table('notificaciones')
    op.drop_index(op.f('ix_incidencias_id_contenedor'), table_name='incidencias')
    op.drop_table('incidencias')
    op.drop_index(op.f('ix_detalles_rutas_id_ruta'), table_name='detalles_rutas')
    op.drop_index(op.f('ix_detalles_rutas_id_contenedor'), table_name='detalles_rutas')
    op.drop_table('detalles_rutas')
    op.drop_index(op.f('ix_contenedores_codigo_contenedor'), table_name='contenedores')
    op.drop_table('contenedores')
    op.drop_table('ubicaciones')
    op.drop_index(op.f('ix_rutas_id_usuario'), table_name='rutas')
    op.drop_table('rutas')
    op.drop_index(op.f('ix_usuarios_codigo_usuario'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_sectores_id_zona'), table_name='sectores')
    op.drop_table('sectores')
    op.drop_table('zonas')
    op.drop_table('tipos_usuarios')
    op.drop_table('tipos_notificacion')
    op.drop_table('motivos_incidencia')
    op.drop_table('estados')
    # ### end Alembic commands ###
